# Bloomberg API Configuration

# Connection settings
bloomberg_host: localhost
bloomberg_port: 8194

# Authentication
bloomberg_auth:
  username: ${BLOOMBERG_USERNAME}
  password: ${BLOOMBERG_PASSWORD}
  api_key: ${BLOOMBERG_API_KEY}
  api_secret: ${BLOOMBERG_API_SECRET}
  api_token: ${BLOOMBERG_API_TOKEN}


# News search settings
news_search:
  topics:
    - "nuclear energy"
    - "nuclear power"
    - "nuclear reactor"
    - "nuclear plant"
    - "nuclear technology"
    - "nuclear waste"
    - "nuclear safety"
    - "nuclear policy"
    - "nuclear regulation"
  max_articles_per_request: 1000
  default_date_range_days: 30
  languages:
    - "en"  # English
    - "fr"  # French
    - "de"  # German
    - "es"  # Spanish
    - "it"  # Italian

# Market data settings
market_data:
  securities:
    - "NUCLEAR INDEX"
    - "NUCLEAR ENERGY COMPANIES"
  fields:
    - "PX_LAST"
    - "VOLUME"
    - "NEWS_SENTIMENT"
    - "PRICE_CHANGE_PCT"
    - "MARKET_CAP"
  update_interval_ms: 5000

# Advanced features
api:
  host: "localhost"
  port: 8194
  max_retries: 3
  timeout_seconds: 30
  rate_limit:
    requests_per_minute: 100
    burst_limit: 150

cache:
  enabled: true
  backend: "redis"
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  ttl_seconds: 3600
  max_size_mb: 1024

data_ingestion:
  batch_size: 1000
  parallel_requests: 4
  max_historical_days: 365
  
  news:
    languages: ["EN", "FR", "DE", "ES", "IT"]
    max_articles_per_request: 50000
    batch_size: 1000
    parallel_requests: 8
    sources:
      - "Bloomberg News"
      - "Reuters"
      - "Financial Times"
      - "World Nuclear News"
      - "Nuclear Engineering International"
      - "Power Engineering"
      - "Scientific American"
      - "Nature Energy"
    keywords:
      - "nuclear energy"
      - "nuclear power"
      - "nuclear reactor"
      - "small modular reactor"
      - "nuclear waste"
      - "uranium"
      - "thorium"
      - "fusion energy"
    historical_data:
      enabled: true
      max_years: 10
      storage: "elasticsearch"

  market_data:
    update_interval_ms: 5000
    fields:
      - "PX_LAST"
      - "VOLUME"
      - "BID"
      - "ASK"
      - "VWAP"
      - "VOLATILITY_10D"
      - "RSI_14D"
      - "MACD"

model:
  architecture: "nuclear_bert"
  training:
    batch_size: 64
    learning_rate: 2e-5
    epochs: 3
    evaluation_steps: 500
    warmup_steps: 1000
    gradient_accumulation_steps: 4
    fp16: true
    
  continuous_learning:
    enabled: true
    trigger:
      new_data_threshold: 10000  # articles
      time_interval: "7d"
    validation:
      holdout_size: 0.2
      min_performance_threshold: 0.85
    
  features:
    text_preprocessing:
      - remove_boilerplate
      - clean_html
      - normalize_whitespace
      - expand_abbreviations
    
    advanced:
      - entity_recognition
      - topic_modeling
      - aspect_based_sentiment
      - temporal_analysis
      - cross_lingual_alignment

storage:
  elasticsearch:
    indices:
      raw_articles: "nuclear_news_raw"
      processed_articles: "nuclear_news_processed"
      sentiment_results: "nuclear_sentiment"
      model_metrics: "model_performance"
    settings:
      shards: 5
      replicas: 1
      refresh_interval: "30s"

  feature_store:
    type: "redis"
    ttl: 86400  # 24 hours
    max_memory: "8gb"

analysis:
  sentiment:
    models:
      - name: "nuclear_bert"
        type: "transformer"
        version: "latest"
      - name: "nuclear_xlnet"
        type: "transformer"
        version: "latest"
      - name: "ensemble"
        type: "voting"
        weights: [0.6, 0.4]
    
    aspects:
      - "safety"
      - "cost"
      - "environmental_impact"
      - "technology"
      - "policy"
      - "public_opinion"
    
    aggregations:
      time_windows:
        - "hourly"
        - "daily"
        - "weekly"
        - "monthly"
        - "quarterly"
      
      dimensions:
        - "source"
        - "language"
        - "aspect"
        - "entity"
        - "topic"

# Monitoring
monitoring:
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    handlers:
      - type: "file"
        filename: "logs/sentiment_analysis.log"
        max_bytes: 10485760  # 10MB
        backup_count: 5
      - type: "elasticsearch"
        index: "sentiment_logs"
  
  metrics:
    enabled: true
    collectors:
      - "model_performance"
      - "data_quality"
      - "processing_time"
      - "api_latency"
    
  alerts:
    channels:
      - type: "email"
        recipients: ["alerts@company.com"]
      - type: "slack"
        channel: "#sentiment-alerts"
    
    rules:
      - name: "data_quality_drop"
        condition: "quality_score < 0.9"
        cooldown_minutes: 60
      - name: "model_performance_degradation"
        condition: "f1_score < 0.85"
        cooldown_minutes: 120
      - name: "processing_delay"
        condition: "lag_minutes > 30"
        cooldown_minutes: 15

# Export
export:
  formats: ["csv", "xlsx", "json", "parquet"]
  scheduling:
    enabled: true
    cron: "0 0 * * *"  # Daily at midnight
  compression: true
  retention_days: 90

# Visualization
visualization:
  dashboard:
    port: 8050
    refresh_interval_seconds: 300
    default_timeframe_days: 30
    
  charts:
    theme: "plotly_dark"
    default_height: 600
    max_points: 10000
    
  export:
    formats: ["csv", "xlsx", "json"]
    auto_schedule: "0 0 * * *"  # Daily at midnight