name: Coverage Report Generator

on:
  workflow_call: {}  # Makes the workflow reusable
  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 UTC daily

permissions:
  contents: write  # Needed to push to main branch

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
          
      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=xml:cobertura.xml
          
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          dotnet-quality: 'ga'
          
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.4.4
        with:
          reports: cobertura.xml
          targetdir: coveragereport
          reporttypes: Html;Html_Light;Html_Dark;Clover;Cobertura;OpenCover;SonarQube;lcov;Latex;LatexSummary;TeamCitySummary;TextSummary;TextDeltaSummary;CsvSummary;MarkdownSummary;MarkdownAssembliesSummary;MarkdownSummaryGithub;Badges
          
      - name: Commit and push report
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add coveragereport/
          git commit -m "Update coverage report [skip ci]"
          git push origin HEAD:main