name: Generate Coverage Report

on:
  workflow_call:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          dotnet-quality: 'ga'

      - name: Generate Report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.4.4
        with:
          reports: cobertura.xml
          targetdir: coveragereport
          reporttypes: Html;Html_Light;Html_Dark;Clover;Cobertura;OpenCover;SonarQube;lcov;Latex;LatexSummary;TeamCitySummary;TextSummary;TextDeltaSummary;CsvSummary;MarkdownSummary;MarkdownAssembliesSummary;MarkdownSummaryGithub;Badges

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport
          path: coveragereport